import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const font = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          font.className +
          " flex h-screen w-screen flex-col divide-y divide-neutral-700 bg-neutral-900 text-neutral-300"
        }
      >
        <header className=" flex h-16 flex-none items-center justify-center">
          header
        </header>
        <main className=" flex flex-grow items-center justify-center">
          {children}
        </main>
        <footer className=" flex h-16 flex-none items-center justify-center">
          footer
        </footer>
      </body>
    </html>
  );
}
