import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " flex h-screen w-screen flex-col"}>
        <header className=" grid  h-12 grid-cols-12 gap-1 bg-slate-500 p-1">
          <h1 className=" col-span-12 flex items-center justify-center">
            header
          </h1>
        </header>
        <main className=" grid flex-grow grid-cols-12 gap-1 p-1">
          {children}
        </main>
        <footer className=" grid  h-12 grid-cols-12 gap-1 bg-slate-500 p-1">
          <h1 className=" col-span-12 flex items-center justify-center">
            footer
          </h1>
        </footer>
      </body>
    </html>
  );
}
