import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const font = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          font.className +
          " flex h-[100dvh] w-[100dvw] flex-col divide-y divide-neutral-700 bg-neutral-900 text-neutral-300"
        }
      >
        <header className=" grid h-16 flex-none place-items-center">
          header
        </header>
        <main className=" grid flex-grow">{children}</main>
        <footer className=" grid h-16 flex-none place-items-center">
          footer
        </footer>
      </body>
    </html>
  );
}
